name: ci

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: Install dependencies
        run: go get .

      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Build
        run: go build -v ./...
